spring:
  application:
    name: spring-crud-task
  datasource:
    url: jdbc:postgresql://${CRUD_DB_HOST:localhost}:${CRUD_DB_PORT:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: sergey.chesnokov9@gmail.com
    password: ofpuyiobibqnkziy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp


geocoder:
  url: https://geocode-maps.yandex.ru/1.x/
  apikey: ${API_KEY_GEO_CODER}


weather:
  url: https://api.weather.yandex.ru/graphql/query
  apikey: ${API_KEY_WEATHER}


