spring:
  application:
    name: spring-crud-task
  datasource:
    url: jdbc:postgresql://${CRUD_DB_HOST:localhost}:${CRUD_DB_PORT:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none
  liquibase:
    url: jdbc:postgresql://${CRUD_DB_HOST:localhost}:${CRUD_DB_PORT:5432}/postgres
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USER_NAME:sergey.chesnokov9@gmail.com}
    password: ${SMTP_PASSWORD:prxd vbks rpey uype}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp


geocoder:
  url: https://geocode-maps.yandex.ru/1.x/
  apikey: ${API_KEY_GEO_CODER:08a201f3-434c-4648-b0a0-464517d6889e}

weather:
  url: https://api.weather.yandex.ru/graphql/query
  apikey: ${API_KEY_WEATHER:0349f327-6eaf-4d57-9d88-38a1e4cdacd0}

advertising:
  minage: 18
  pagination:
    page-size: 5

scheduling:
  timing: 2
