spring:
  application:
    name: spring-crud-task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update


geocoder:
  url: https://geocode-maps.yandex.ru/1.x/
  apikey: ${API_KEY_GEO_CODER}


weather:
  url: https://api.weather.yandex.ru/graphql/query
  apikey: ${API_KEY_WEATHER}


